---
# tasks file for jenkins-centos6


- name: Add Jenkins yum repository file
  copy: src=jenkins.repo dest=/etc/yum.repos.d/jenkins.repo  owner=root group=root mode=0644

- name: Add Jenkins gpg key
  rpm_key: state=present key=https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins stable
  yum: name=jenkins state=latest

- name: Start & enable Jenkins at boot time.
  service: name=jenkins  state=started enabled=yes
